### ISSUE TITLE
CSS framework?

### ISSUE THREAD

**Issue by naliwajek** [naliwajek/roda-learning#1]
I added `neat` gem from thoughtbot to the Gemfile but I have problems setting assets in Roda. 

Any help will be greatly appreciated.

**Comment by naliwajek** [comment]
Looks cool: http://purecss.io

Me wanna learn. Change it if you have anything against.

**Comment by matDobek** [comment]
:+1: 
I like that we use _almost_ the same stack as in @netguru

**Comment by naliwajek** [comment]
Haha.
